-- Table: dsa.recien_graduado

-- DROP TABLE dsa.recien_graduado;

CREATE TABLE dsa.recien_graduado
(
  id serial NOT NULL,
  usuario character varying,
  nro_doc character varying,
  fecha_nac character varying,
  sexo character varying,
  nacionalidad character varying,
  mail character varying,
  estado_civil character varying,
  cant_hijos character varying,
  grupo_conv character varying,
  titulo character varying,
  ciudad_res character varying,
  prov_res character varying,
  pais_res character varying,
  ciudad_proc character varying,
  prov_proc character varying,
  pais_proc character varying,
  hab_lectura character varying,
  tipo_lectura character varying,
  otros_hab character varying,
  estudio_padre character varying,
  estudio_madre character varying,
  estudio_pareja character varying,
  cond_actual character varying,
  busca_trab character varying,
  exp_laboral character varying,
  caract_val_empleador character varying,
  otras_capacidades character varying,
  otras_fuentes_lab character varying,
  info_bolsa_trab character varying,
  recibe_remun character varying,
  realiza_aporte_jub character varying,
  tipo_relacion_lab character varying,
  tipo_contratacion character varying,
  cant_hs_semanal character varying,
  satisfecho_trabajo character varying,
  entidad_trabaja character varying,
  mejora_por_titulo character varying,
  razon_no_trabaja character varying,
  sector_pref character varying,
  activ_pref character varying,
  exig_lugar_trabajo character varying,
  motivo_elec_carrera character varying,
  motivo_estud_univer character varying,
  cont_carrera_interes character varying,
  cont_carrera_expec character varying,
  nivel_exigencia_carrera character varying,
  plan_estudio_corto character varying,
  plan_estudio_largo character varying,
  plan_estudio_tecnico character varying,
  plan_estudio_gral character varying,
  opinion_alum character varying,
  opinion_aulas character varying,
  opinion_biblio character varying,
  opinion_lab character varying,
  opinion_admin character varying,
  volver_univer character varying,
  aspectos_univer_aprecia character varying,
  reconom_univer_socie character varying,
  brindar_univer character varying,
  otros_estudios character varying,
  tipo_institucion character varying,
  nombre_carrera character varying,
  finalizo_carrera character varying,
  conoc_ingles character varying,
  conoc_frances character varying,
  conoc_aleman character varying,
  conoc_italiano character varying,
  conoc_portugues character varying,
  conoc_herr_infor character varying,
  seguir_estud character varying,
  que_seguir_estud character varying,
  donde_seguir_estud character varying,
  porque_seguir_estud character varying,
  interes_formac_continua character varying,
  fecha_inicio_enc date,
  fecha_fin_enc date,
  anio_ingreso character varying,
  CONSTRAINT pk_recieng PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE dsa.recien_graduado
  OWNER TO postgres;

